-- phpMyAdmin SQL Dump
-- version 5.0.4
-- https://www.phpmyadmin.net/
--
-- Hôte : localhost:8889
-- Généré le : mar. 25 mai 2021 à 21:51
-- Version du serveur :  5.7.32
-- Version de PHP : 7.4.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

--
-- Base de données : `base-de-donnees`
--

-- --------------------------------------------------------

--
-- Structure de la table `categories`
--

CREATE TABLE `categories` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Déchargement des données de la table `categories`
--

INSERT INTO `categories` (`id`, `name`) VALUES
(1, 'Ordinateurs'),
(2, 'Ordinateurs Portables'),
(3, 'Tablettes'),
(4, 'Accessoires');

-- --------------------------------------------------------

--
-- Structure de la table `orders`
--

CREATE TABLE `orders` (
  `id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `amount` float NOT NULL,
  `created` datetime NOT NULL,
  `datas` text NOT NULL,
  `txn_id` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `orders`
--

INSERT INTO `orders` (`id`, `user_id`, `amount`, `created`, `datas`, `txn_id`) VALUES
(26, 1, 49.98, '2012-12-16 20:53:08', 'a:53:{s:8:\"mc_gross\";s:5:\"49.98\";s:22:\"protection_eligibility\";s:10:\"Ineligible\";s:14:\"address_status\";s:11:\"unconfirmed\";s:12:\"item_number1\";s:2:\"45\";s:3:\"tax\";s:4:\"0.00\";s:12:\"item_number2\";s:2:\"55\";s:8:\"payer_id\";s:13:\"49XB7FERH7E2Q\";s:14:\"address_street\";s:33:\"Av. de la Pelouse, 87648672 Mayet\";s:12:\"payment_date\";s:25:\"11:53:00 Dec 16, 2012 PST\";s:14:\"payment_status\";s:9:\"Completed\";s:7:\"charset\";s:12:\"windows-1252\";s:11:\"address_zip\";s:5:\"75002\";s:11:\"mc_shipping\";s:4:\"0.00\";s:11:\"mc_handling\";s:4:\"0.00\";s:10:\"first_name\";s:7:\"athakim\";s:6:\"mc_fee\";s:4:\"1.95\";s:20:\"address_country_code\";s:2:\"FR\";s:12:\"address_name\";s:15:\"athakim Sandbox\";s:14:\"notify_version\";s:3:\"3.7\";s:6:\"custom\";s:9:\"user_id=1\";s:12:\"payer_status\";s:8:\"verified\";s:8:\"business\";s:29:\"vendre_1355601370_biz@live.fr\";s:15:\"address_country\";s:6:\"France\";s:14:\"num_cart_items\";s:1:\"2\";s:12:\"mc_handling1\";s:4:\"0.00\";s:12:\"mc_handling2\";s:4:\"0.00\";s:12:\"address_city\";s:5:\"Paris\";s:11:\"verify_sign\";s:56:\"Ac5d7Hoagxb9fdX-KmTBG7cXlhWWAiQ2H0ghMbOdN0mRAdOc7IrYCX4e\";s:11:\"payer_email\";s:29:\"achete_1355601319_per@live.fr\";s:12:\"mc_shipping1\";s:4:\"0.00\";s:12:\"mc_shipping2\";s:4:\"0.00\";s:4:\"tax1\";s:4:\"0.00\";s:4:\"tax2\";s:4:\"0.00\";s:6:\"txn_id\";s:17:\"10N820126F771591J\";s:12:\"payment_type\";s:7:\"instant\";s:9:\"last_name\";s:7:\"Sandbox\";s:13:\"address_state\";s:6:\"Alsace\";s:10:\"item_name1\";s:11:\"Magic mouse\";s:14:\"receiver_email\";s:29:\"vendre_1355601370_biz@live.fr\";s:10:\"item_name2\";s:10:\"Accessoire\";s:11:\"payment_fee\";s:0:\"\";s:9:\"quantity1\";s:1:\"1\";s:9:\"quantity2\";s:1:\"1\";s:11:\"receiver_id\";s:13:\"ZWU5WZUEP4QK6\";s:8:\"txn_type\";s:4:\"cart\";s:10:\"mc_gross_1\";s:5:\"29.99\";s:11:\"mc_currency\";s:3:\"EUR\";s:10:\"mc_gross_2\";s:5:\"19.99\";s:17:\"residence_country\";s:2:\"FR\";s:8:\"test_ipn\";s:1:\"1\";s:19:\"transaction_subject\";s:9:\"user_id=1\";s:13:\"payment_gross\";s:0:\"\";s:12:\"ipn_track_id\";s:13:\"5f3aa3787c3bf\";}', '10N820126F771591J'),
(27, 1, 618.99, '2012-12-16 20:56:08', 'a:53:{s:8:\"mc_gross\";s:6:\"618.99\";s:22:\"protection_eligibility\";s:10:\"Ineligible\";s:14:\"address_status\";s:11:\"unconfirmed\";s:12:\"item_number1\";s:2:\"54\";s:3:\"tax\";s:4:\"0.00\";s:12:\"item_number2\";s:2:\"55\";s:8:\"payer_id\";s:13:\"49XB7FERH7E2Q\";s:14:\"address_street\";s:33:\"Av. de la Pelouse, 87648672 Mayet\";s:12:\"payment_date\";s:25:\"11:56:00 Dec 16, 2012 PST\";s:14:\"payment_status\";s:9:\"Completed\";s:7:\"charset\";s:12:\"windows-1252\";s:11:\"address_zip\";s:5:\"75002\";s:11:\"mc_shipping\";s:4:\"0.00\";s:11:\"mc_handling\";s:4:\"0.00\";s:10:\"first_name\";s:7:\"athakim\";s:6:\"mc_fee\";s:5:\"21.30\";s:20:\"address_country_code\";s:2:\"FR\";s:12:\"address_name\";s:15:\"athakim Sandbox\";s:14:\"notify_version\";s:3:\"3.7\";s:6:\"custom\";s:9:\"user_id=1\";s:12:\"payer_status\";s:8:\"verified\";s:8:\"business\";s:29:\"vendre_1355601370_biz@live.fr\";s:15:\"address_country\";s:6:\"France\";s:14:\"num_cart_items\";s:1:\"2\";s:12:\"mc_handling1\";s:4:\"0.00\";s:12:\"mc_handling2\";s:4:\"0.00\";s:12:\"address_city\";s:5:\"Paris\";s:11:\"verify_sign\";s:56:\"AFcWxV21C7fd0v3bYYYRCpSSRl31ApLWnEZXLzdzdurQxcBZL0f8zI97\";s:11:\"payer_email\";s:29:\"achete_1355601319_per@live.fr\";s:12:\"mc_shipping1\";s:4:\"0.00\";s:12:\"mc_shipping2\";s:4:\"0.00\";s:4:\"tax1\";s:4:\"0.00\";s:4:\"tax2\";s:4:\"0.00\";s:6:\"txn_id\";s:17:\"44662988A6831473C\";s:12:\"payment_type\";s:7:\"instant\";s:9:\"last_name\";s:7:\"Sandbox\";s:13:\"address_state\";s:6:\"Alsace\";s:10:\"item_name1\";s:4:\"Ipad\";s:14:\"receiver_email\";s:29:\"vendre_1355601370_biz@live.fr\";s:10:\"item_name2\";s:10:\"Accessoire\";s:11:\"payment_fee\";s:0:\"\";s:9:\"quantity1\";s:1:\"1\";s:9:\"quantity2\";s:1:\"1\";s:11:\"receiver_id\";s:13:\"ZWU5WZUEP4QK6\";s:8:\"txn_type\";s:4:\"cart\";s:10:\"mc_gross_1\";s:6:\"599.00\";s:11:\"mc_currency\";s:3:\"EUR\";s:10:\"mc_gross_2\";s:5:\"19.99\";s:17:\"residence_country\";s:2:\"FR\";s:8:\"test_ipn\";s:1:\"1\";s:19:\"transaction_subject\";s:9:\"user_id=1\";s:13:\"payment_gross\";s:0:\"\";s:12:\"ipn_track_id\";s:13:\"fdd06ab988268\";}', '44662988A6831473C'),
(28, 1, 69.97, '2012-12-16 20:59:51', 'a:53:{s:8:\"mc_gross\";s:5:\"69.97\";s:22:\"protection_eligibility\";s:10:\"Ineligible\";s:14:\"address_status\";s:11:\"unconfirmed\";s:12:\"item_number1\";s:2:\"44\";s:3:\"tax\";s:4:\"0.00\";s:12:\"item_number2\";s:2:\"55\";s:8:\"payer_id\";s:13:\"49XB7FERH7E2Q\";s:14:\"address_street\";s:33:\"Av. de la Pelouse, 87648672 Mayet\";s:12:\"payment_date\";s:25:\"11:59:44 Dec 16, 2012 PST\";s:14:\"payment_status\";s:9:\"Completed\";s:7:\"charset\";s:12:\"windows-1252\";s:11:\"address_zip\";s:5:\"75002\";s:11:\"mc_shipping\";s:4:\"0.00\";s:11:\"mc_handling\";s:4:\"0.00\";s:10:\"first_name\";s:7:\"athakim\";s:6:\"mc_fee\";s:4:\"2.63\";s:20:\"address_country_code\";s:2:\"FR\";s:12:\"address_name\";s:15:\"athakim Sandbox\";s:14:\"notify_version\";s:3:\"3.7\";s:6:\"custom\";s:9:\"user_id=1\";s:12:\"payer_status\";s:8:\"verified\";s:8:\"business\";s:29:\"vendre_1355601370_biz@live.fr\";s:15:\"address_country\";s:6:\"France\";s:14:\"num_cart_items\";s:1:\"2\";s:12:\"mc_handling1\";s:4:\"0.00\";s:12:\"mc_handling2\";s:4:\"0.00\";s:12:\"address_city\";s:5:\"Paris\";s:11:\"verify_sign\";s:56:\"Adbz0m5-guW6f00LVbD9wZ-Y2wIpAcnXE6A1u4AIszE8OrK258JDGcmh\";s:11:\"payer_email\";s:29:\"achete_1355601319_per@live.fr\";s:12:\"mc_shipping1\";s:4:\"0.00\";s:12:\"mc_shipping2\";s:4:\"0.00\";s:4:\"tax1\";s:4:\"0.00\";s:4:\"tax2\";s:4:\"0.00\";s:6:\"txn_id\";s:17:\"2NR105782D636505W\";s:12:\"payment_type\";s:7:\"instant\";s:9:\"last_name\";s:7:\"Sandbox\";s:13:\"address_state\";s:6:\"Alsace\";s:10:\"item_name1\";s:16:\"Clavier pour Mac\";s:14:\"receiver_email\";s:29:\"vendre_1355601370_biz@live.fr\";s:10:\"item_name2\";s:10:\"Accessoire\";s:11:\"payment_fee\";s:0:\"\";s:9:\"quantity1\";s:1:\"1\";s:9:\"quantity2\";s:1:\"2\";s:11:\"receiver_id\";s:13:\"ZWU5WZUEP4QK6\";s:8:\"txn_type\";s:4:\"cart\";s:10:\"mc_gross_1\";s:5:\"29.99\";s:11:\"mc_currency\";s:3:\"EUR\";s:10:\"mc_gross_2\";s:5:\"39.98\";s:17:\"residence_country\";s:2:\"FR\";s:8:\"test_ipn\";s:1:\"1\";s:19:\"transaction_subject\";s:9:\"user_id=1\";s:13:\"payment_gross\";s:0:\"\";s:12:\"ipn_track_id\";s:13:\"54a7e60b73b99\";}', '2NR105782D636505W'),
(29, 1, 49.98, '2012-12-16 21:01:36', 'a:53:{s:8:\"mc_gross\";s:5:\"49.98\";s:22:\"protection_eligibility\";s:10:\"Ineligible\";s:14:\"address_status\";s:11:\"unconfirmed\";s:12:\"item_number1\";s:2:\"44\";s:3:\"tax\";s:4:\"0.00\";s:12:\"item_number2\";s:2:\"55\";s:8:\"payer_id\";s:13:\"49XB7FERH7E2Q\";s:14:\"address_street\";s:33:\"Av. de la Pelouse, 87648672 Mayet\";s:12:\"payment_date\";s:25:\"12:01:32 Dec 16, 2012 PST\";s:14:\"payment_status\";s:9:\"Completed\";s:7:\"charset\";s:12:\"windows-1252\";s:11:\"address_zip\";s:5:\"75002\";s:11:\"mc_shipping\";s:4:\"0.00\";s:11:\"mc_handling\";s:4:\"0.00\";s:10:\"first_name\";s:7:\"athakim\";s:6:\"mc_fee\";s:4:\"1.95\";s:20:\"address_country_code\";s:2:\"FR\";s:12:\"address_name\";s:15:\"athakim Sandbox\";s:14:\"notify_version\";s:3:\"3.7\";s:6:\"custom\";s:9:\"user_id=1\";s:12:\"payer_status\";s:8:\"verified\";s:8:\"business\";s:29:\"vendre_1355601370_biz@live.fr\";s:15:\"address_country\";s:6:\"France\";s:14:\"num_cart_items\";s:1:\"2\";s:12:\"mc_handling1\";s:4:\"0.00\";s:12:\"mc_handling2\";s:4:\"0.00\";s:12:\"address_city\";s:5:\"Paris\";s:11:\"verify_sign\";s:56:\"AFcWxV21C7fd0v3bYYYRCpSSRl31AxDI97chVz1T5UV12GnaNPelx.El\";s:11:\"payer_email\";s:29:\"achete_1355601319_per@live.fr\";s:12:\"mc_shipping1\";s:4:\"0.00\";s:12:\"mc_shipping2\";s:4:\"0.00\";s:4:\"tax1\";s:4:\"0.00\";s:4:\"tax2\";s:4:\"0.00\";s:6:\"txn_id\";s:17:\"05960893Y8536205H\";s:12:\"payment_type\";s:7:\"instant\";s:9:\"last_name\";s:7:\"Sandbox\";s:13:\"address_state\";s:6:\"Alsace\";s:10:\"item_name1\";s:16:\"Clavier pour Mac\";s:14:\"receiver_email\";s:29:\"vendre_1355601370_biz@live.fr\";s:10:\"item_name2\";s:10:\"Accessoire\";s:11:\"payment_fee\";s:0:\"\";s:9:\"quantity1\";s:1:\"1\";s:9:\"quantity2\";s:1:\"1\";s:11:\"receiver_id\";s:13:\"ZWU5WZUEP4QK6\";s:8:\"txn_type\";s:4:\"cart\";s:10:\"mc_gross_1\";s:5:\"29.99\";s:11:\"mc_currency\";s:3:\"EUR\";s:10:\"mc_gross_2\";s:5:\"19.99\";s:17:\"residence_country\";s:2:\"FR\";s:8:\"test_ipn\";s:1:\"1\";s:19:\"transaction_subject\";s:9:\"user_id=1\";s:13:\"payment_gross\";s:0:\"\";s:12:\"ipn_track_id\";s:13:\"c454d3a5a97b1\";}', '05960893Y8536205H'),
(30, 1, 19.99, '2012-12-16 21:04:33', 'a:46:{s:8:\"mc_gross\";s:5:\"19.99\";s:22:\"protection_eligibility\";s:10:\"Ineligible\";s:14:\"address_status\";s:11:\"unconfirmed\";s:12:\"item_number1\";s:2:\"55\";s:8:\"payer_id\";s:13:\"49XB7FERH7E2Q\";s:3:\"tax\";s:4:\"0.00\";s:14:\"address_street\";s:33:\"Av. de la Pelouse, 87648672 Mayet\";s:12:\"payment_date\";s:25:\"12:04:26 Dec 16, 2012 PST\";s:14:\"payment_status\";s:9:\"Completed\";s:7:\"charset\";s:12:\"windows-1252\";s:11:\"address_zip\";s:5:\"75002\";s:11:\"mc_shipping\";s:4:\"0.00\";s:11:\"mc_handling\";s:4:\"0.00\";s:10:\"first_name\";s:7:\"athakim\";s:6:\"mc_fee\";s:4:\"0.93\";s:20:\"address_country_code\";s:2:\"FR\";s:12:\"address_name\";s:15:\"athakim Sandbox\";s:14:\"notify_version\";s:3:\"3.7\";s:6:\"custom\";s:9:\"user_id=1\";s:12:\"payer_status\";s:8:\"verified\";s:8:\"business\";s:29:\"vendre_1355601370_biz@live.fr\";s:15:\"address_country\";s:6:\"France\";s:14:\"num_cart_items\";s:1:\"1\";s:12:\"mc_handling1\";s:4:\"0.00\";s:12:\"address_city\";s:5:\"Paris\";s:11:\"verify_sign\";s:56:\"AmGoBKHOSe9w7wrilfKlBhfMaMG3Al4AWw5KHNL-hSNJkLco-t-5RwMr\";s:11:\"payer_email\";s:29:\"achete_1355601319_per@live.fr\";s:12:\"mc_shipping1\";s:4:\"0.00\";s:4:\"tax1\";s:4:\"0.00\";s:6:\"txn_id\";s:17:\"3BC71542YD418670U\";s:12:\"payment_type\";s:7:\"instant\";s:9:\"last_name\";s:7:\"Sandbox\";s:13:\"address_state\";s:6:\"Alsace\";s:10:\"item_name1\";s:10:\"Accessoire\";s:14:\"receiver_email\";s:29:\"vendre_1355601370_biz@live.fr\";s:11:\"payment_fee\";s:0:\"\";s:9:\"quantity1\";s:1:\"1\";s:11:\"receiver_id\";s:13:\"ZWU5WZUEP4QK6\";s:8:\"txn_type\";s:4:\"cart\";s:10:\"mc_gross_1\";s:5:\"19.99\";s:11:\"mc_currency\";s:3:\"EUR\";s:17:\"residence_country\";s:2:\"FR\";s:8:\"test_ipn\";s:1:\"1\";s:19:\"transaction_subject\";s:9:\"user_id=1\";s:13:\"payment_gross\";s:0:\"\";s:12:\"ipn_track_id\";s:13:\"fb0d1e285c5da\";}', '3BC71542YD418670U'),
(31, 1, 19.99, '2012-12-16 21:08:21', 'a:46:{s:8:\"mc_gross\";s:5:\"19.99\";s:22:\"protection_eligibility\";s:10:\"Ineligible\";s:14:\"address_status\";s:11:\"unconfirmed\";s:12:\"item_number1\";s:2:\"55\";s:8:\"payer_id\";s:13:\"49XB7FERH7E2Q\";s:3:\"tax\";s:4:\"0.00\";s:14:\"address_street\";s:33:\"Av. de la Pelouse, 87648672 Mayet\";s:12:\"payment_date\";s:25:\"12:08:17 Dec 16, 2012 PST\";s:14:\"payment_status\";s:9:\"Completed\";s:7:\"charset\";s:12:\"windows-1252\";s:11:\"address_zip\";s:5:\"75002\";s:11:\"mc_shipping\";s:4:\"0.00\";s:11:\"mc_handling\";s:4:\"0.00\";s:10:\"first_name\";s:7:\"athakim\";s:6:\"mc_fee\";s:4:\"0.93\";s:20:\"address_country_code\";s:2:\"FR\";s:12:\"address_name\";s:15:\"athakim Sandbox\";s:14:\"notify_version\";s:3:\"3.7\";s:6:\"custom\";s:9:\"user_id=1\";s:12:\"payer_status\";s:8:\"verified\";s:8:\"business\";s:29:\"vendre_1355601370_biz@live.fr\";s:15:\"address_country\";s:6:\"France\";s:14:\"num_cart_items\";s:1:\"1\";s:12:\"mc_handling1\";s:4:\"0.00\";s:12:\"address_city\";s:5:\"Paris\";s:11:\"verify_sign\";s:56:\"AlZ1qGkQy2QC7BmIyGDa44TEawnyAFXQNzhFUHI1BJvpd-QC0erX0PXs\";s:11:\"payer_email\";s:29:\"achete_1355601319_per@live.fr\";s:12:\"mc_shipping1\";s:4:\"0.00\";s:4:\"tax1\";s:4:\"0.00\";s:6:\"txn_id\";s:17:\"8Y315627BG7716739\";s:12:\"payment_type\";s:7:\"instant\";s:9:\"last_name\";s:7:\"Sandbox\";s:13:\"address_state\";s:6:\"Alsace\";s:10:\"item_name1\";s:10:\"Accessoire\";s:14:\"receiver_email\";s:29:\"vendre_1355601370_biz@live.fr\";s:11:\"payment_fee\";s:0:\"\";s:9:\"quantity1\";s:1:\"1\";s:11:\"receiver_id\";s:13:\"ZWU5WZUEP4QK6\";s:8:\"txn_type\";s:4:\"cart\";s:10:\"mc_gross_1\";s:5:\"19.99\";s:11:\"mc_currency\";s:3:\"EUR\";s:17:\"residence_country\";s:2:\"FR\";s:8:\"test_ipn\";s:1:\"1\";s:19:\"transaction_subject\";s:9:\"user_id=1\";s:13:\"payment_gross\";s:0:\"\";s:12:\"ipn_track_id\";s:13:\"b711fd3895c35\";}', '8Y315627BG7716739'),
(32, 1, 29.99, '2012-12-16 21:16:54', 'a:46:{s:8:\"mc_gross\";s:5:\"29.99\";s:22:\"protection_eligibility\";s:10:\"Ineligible\";s:14:\"address_status\";s:11:\"unconfirmed\";s:12:\"item_number1\";s:2:\"50\";s:8:\"payer_id\";s:13:\"49XB7FERH7E2Q\";s:3:\"tax\";s:4:\"0.00\";s:14:\"address_street\";s:33:\"Av. de la Pelouse, 87648672 Mayet\";s:12:\"payment_date\";s:25:\"12:16:49 Dec 16, 2012 PST\";s:14:\"payment_status\";s:9:\"Completed\";s:7:\"charset\";s:12:\"windows-1252\";s:11:\"address_zip\";s:5:\"75002\";s:11:\"mc_shipping\";s:4:\"0.00\";s:11:\"mc_handling\";s:4:\"0.00\";s:10:\"first_name\";s:7:\"athakim\";s:6:\"mc_fee\";s:4:\"1.27\";s:20:\"address_country_code\";s:2:\"FR\";s:12:\"address_name\";s:15:\"athakim Sandbox\";s:14:\"notify_version\";s:3:\"3.7\";s:6:\"custom\";s:9:\"user_id=1\";s:12:\"payer_status\";s:8:\"verified\";s:8:\"business\";s:29:\"vendre_1355601370_biz@live.fr\";s:15:\"address_country\";s:6:\"France\";s:14:\"num_cart_items\";s:1:\"1\";s:12:\"mc_handling1\";s:4:\"0.00\";s:12:\"address_city\";s:5:\"Paris\";s:11:\"verify_sign\";s:56:\"AA-YUlrlPY97jvy6Q1MtmXKdUAydAlkSeAkQQOqfH97R.zIVFh-08krC\";s:11:\"payer_email\";s:29:\"achete_1355601319_per@live.fr\";s:12:\"mc_shipping1\";s:4:\"0.00\";s:4:\"tax1\";s:4:\"0.00\";s:6:\"txn_id\";s:17:\"8HU40926R5396104D\";s:12:\"payment_type\";s:7:\"instant\";s:9:\"last_name\";s:7:\"Sandbox\";s:13:\"address_state\";s:6:\"Alsace\";s:10:\"item_name1\";s:11:\"Magic mouse\";s:14:\"receiver_email\";s:29:\"vendre_1355601370_biz@live.fr\";s:11:\"payment_fee\";s:0:\"\";s:9:\"quantity1\";s:1:\"1\";s:11:\"receiver_id\";s:13:\"ZWU5WZUEP4QK6\";s:8:\"txn_type\";s:4:\"cart\";s:10:\"mc_gross_1\";s:5:\"29.99\";s:11:\"mc_currency\";s:3:\"EUR\";s:17:\"residence_country\";s:2:\"FR\";s:8:\"test_ipn\";s:1:\"1\";s:19:\"transaction_subject\";s:9:\"user_id=1\";s:13:\"payment_gross\";s:0:\"\";s:12:\"ipn_track_id\";s:13:\"2d39753011548\";}', '8HU40926R5396104D'),
(33, 1, 19.99, '2012-12-16 22:09:12', 'a:46:{s:8:\"mc_gross\";s:5:\"19.99\";s:22:\"protection_eligibility\";s:10:\"Ineligible\";s:14:\"address_status\";s:11:\"unconfirmed\";s:12:\"item_number1\";s:2:\"55\";s:8:\"payer_id\";s:13:\"49XB7FERH7E2Q\";s:3:\"tax\";s:4:\"0.00\";s:14:\"address_street\";s:33:\"Av. de la Pelouse, 87648672 Mayet\";s:12:\"payment_date\";s:25:\"13:09:06 Dec 16, 2012 PST\";s:14:\"payment_status\";s:9:\"Completed\";s:7:\"charset\";s:12:\"windows-1252\";s:11:\"address_zip\";s:5:\"75002\";s:11:\"mc_shipping\";s:4:\"0.00\";s:11:\"mc_handling\";s:4:\"0.00\";s:10:\"first_name\";s:7:\"athakim\";s:6:\"mc_fee\";s:4:\"0.93\";s:20:\"address_country_code\";s:2:\"FR\";s:12:\"address_name\";s:15:\"athakim Sandbox\";s:14:\"notify_version\";s:3:\"3.7\";s:6:\"custom\";s:9:\"user_id=1\";s:12:\"payer_status\";s:8:\"verified\";s:8:\"business\";s:29:\"vendre_1355601370_biz@live.fr\";s:15:\"address_country\";s:6:\"France\";s:14:\"num_cart_items\";s:1:\"1\";s:12:\"mc_handling1\";s:4:\"0.00\";s:12:\"address_city\";s:5:\"Paris\";s:11:\"verify_sign\";s:56:\"A7g-gYAFvcwz1Vr1JdRNl8cwGF5BATeETahuZtPJ9B5vPdlifI640kqy\";s:11:\"payer_email\";s:29:\"achete_1355601319_per@live.fr\";s:12:\"mc_shipping1\";s:4:\"0.00\";s:4:\"tax1\";s:4:\"0.00\";s:6:\"txn_id\";s:17:\"5JC30947PM3464408\";s:12:\"payment_type\";s:7:\"instant\";s:9:\"last_name\";s:7:\"Sandbox\";s:13:\"address_state\";s:6:\"Alsace\";s:10:\"item_name1\";s:10:\"Accessoire\";s:14:\"receiver_email\";s:29:\"vendre_1355601370_biz@live.fr\";s:11:\"payment_fee\";s:0:\"\";s:9:\"quantity1\";s:1:\"1\";s:11:\"receiver_id\";s:13:\"ZWU5WZUEP4QK6\";s:8:\"txn_type\";s:4:\"cart\";s:10:\"mc_gross_1\";s:5:\"19.99\";s:11:\"mc_currency\";s:3:\"EUR\";s:17:\"residence_country\";s:2:\"FR\";s:8:\"test_ipn\";s:1:\"1\";s:19:\"transaction_subject\";s:9:\"user_id=1\";s:13:\"payment_gross\";s:0:\"\";s:12:\"ipn_track_id\";s:13:\"d0dd997f5380e\";}', '5JC30947PM3464408');

-- --------------------------------------------------------

--
-- Structure de la table `products`
--

CREATE TABLE `products` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `price` float NOT NULL DEFAULT '0',
  `qte` int(10) UNSIGNED NOT NULL,
  `photo` varchar(255) NOT NULL,
  `category_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Déchargement des données de la table `products`
--

INSERT INTO `products` (`id`, `name`, `description`, `price`, `qte`, `photo`, `category_id`) VALUES
(1, 'Mac 27 Pouces', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 1499, 10, 'img/produits/mac.png', 1),
(2, 'Mac book pro', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 1999, 10, 'img/produits/macbook.png', 2),
(4, 'Clavier pour Mac', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 29.99, 10, 'img/produits/clavier.png', 4),
(5, 'Accessoire', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 19.99, 10, 'img/produits/acc.png', 4),
(6, 'Ipad', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 599, 10, 'img/produits/ipad.png', 3),
(7, 'Mac 27 Pouces', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 1499, 10, 'img/produits/mac.png', 1),
(8, 'Clavier pour Mac', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 29.99, 10, 'img/produits/clavier.png', 4),
(9, 'Ipad', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 599, 10, 'img/produits/ipad.png', 3),
(10, 'Magic mouse', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 29.99, 10, 'img/produits/souris.png', 4),
(11, 'Mac 27 Pouces', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 1499, 10, 'img/produits/mac.png', 1),
(12, 'Clavier pour Mac', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 29.99, 10, 'img/produits/clavier.png', 4),
(13, 'Mac 27 Pouces', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 1499, 10, 'img/produits/mac.png', 1),
(14, 'Mac book pro', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 1999, 10, 'img/produits/macbook.png', 2),
(15, 'Magic mouse', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 29.99, 10, 'img/produits/souris.png', 4),
(16, 'Clavier pour Mac', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 29.99, 10, 'img/produits/clavier.png', 4),
(17, 'Mac 27 Pouces', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 1499, 10, 'img/produits/mac.png', 1),
(18, 'Ipad', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 599, 10, 'img/produits/ipad.png', 3),
(19, 'Mac 27 Pouces', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 1499, 10, 'img/produits/mac.png', 1),
(20, 'Magic mouse', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 29.99, 10, 'img/produits/souris.png', 4),
(21, 'Ipad', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 599, 10, 'img/produits/ipad.png', 3),
(22, 'Mac book pro', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 1999, 10, 'img/produits/macbook.png', 2),
(23, 'Mac 27 Pouces', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 1499, 10, 'img/produits/mac.png', 1),
(24, 'Clavier pour Mac', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 29.99, 10, 'img/produits/clavier.png', 4),
(25, 'Accessoire', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 19.99, 10, 'img/produits/acc.png', 4),
(26, 'Mac book pro', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 1999, 10, 'img/produits/macbook.png', 2),
(27, 'Ipad', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 599, 10, 'img/produits/ipad.png', 3),
(28, 'Clavier pour Mac', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 29.99, 10, 'img/produits/clavier.png', 4),
(29, 'Mac 27 Pouces', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 1499, 10, 'img/produits/mac.png', 1),
(30, 'Magic mouse', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 29.99, 10, 'img/produits/souris.png', 4),
(31, 'Mac 27 Pouces', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 1499, 10, 'img/produits/mac.png', 1),
(32, 'Clavier pour Mac', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 29.99, 10, 'img/produits/clavier.png', 4),
(33, 'Ipad', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 599, 10, 'img/produits/ipad.png', 3),
(34, 'Mac book pro', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 1999, 10, 'img/produits/macbook.png', 2),
(35, 'Accessoire', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 19.99, 10, 'img/produits/acc.png', 4),
(36, 'Clavier pour Mac', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 29.99, 10, 'img/produits/clavier.png', 4),
(37, 'Mac 27 Pouces', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 1499, 10, 'img/produits/mac.png', 1),
(38, 'Mac book pro', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 1999, 10, 'img/produits/macbook.png', 2),
(39, 'Ipad', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 599, 10, 'img/produits/ipad.png', 3),
(40, 'Magic mouse', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 29.99, 10, 'img/produits/souris.png', 4),
(41, 'Mac 27 Pouces', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 1499, 10, 'img/produits/mac.png', 1),
(42, 'Ipad', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 599, 10, 'img/produits/ipad.png', 3),
(43, 'Mac 27 Pouces', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 1499, 10, 'img/produits/mac.png', 1),
(44, 'Clavier pour Mac', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 29.99, 10, 'img/produits/clavier.png', 4),
(45, 'Magic mouse', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 29.99, 10, 'img/produits/souris.png', 4),
(46, 'Mac book pro', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 1999, 10, 'img/produits/macbook.png', 2),
(47, 'Mac 27 Pouces', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 1499, 10, 'img/produits/mac.png', 1),
(48, 'Clavier pour Mac', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 29.99, 10, 'img/produits/clavier.png', 4),
(49, 'Mac 27 Pouces', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 1499, 10, 'img/produits/mac.png', 1),
(50, 'Magic mouse', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 29.99, 10, 'img/produits/souris.png', 4),
(51, 'Ipad', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 599, 10, 'img/produits/ipad.png', 3),
(52, 'Clavier pour Mac', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 29.99, 10, 'img/produits/clavier.png', 4),
(53, 'Mac 27 Pouces', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 1499, 10, 'img/produits/mac.png', 1),
(54, 'Ipad', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 599, 10, 'img/produits/ipad.png', 3),
(55, 'Accessoire', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 19.99, 10, 'img/produits/acc.png', 4),
(56, 'Clavier pour Mac', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 29.99, 10, 'img/produits/clavier.png', 4),
(57, 'Ipad', 'Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 599, 11, 'img/produits/ipad.png', 3),
(58, 'Mac book pro', '232 Elementum odio pulvinar lorem mid! Platea pid dolor odio? Ultricies porttitor vel! Pulvinar, vut dolor sed, amet, nisi natoque enim risus habitasse mid rhoncus! Aenean nunc in massa est montes, parturient porttitor a platea! Nec augue, eros etiam augue hac scelerisque urna aliquet duis, in et mid phasellus. Porttitor et pulvinar hac aliquam pid, nisi nunc. Dignissim montes etiam pid? Sagittis adipiscing porttitor eros platea phasellus vel pulvinar risus duis, hac phasellus ac a placerat diam augue et ac turpis. Et, a purus nec. Risus scelerisque tortor tincidunt parturient. Aliquet. Dapibus non montes urna dictumst ultrices. Vel massa vel in porta aenean porta nascetur augue enim elementum integer. Mattis montes platea aliquam odio aliquet magna elementum magna qui', 1999, 10, 'img/produits/macbook.png', 2);

-- --------------------------------------------------------

--
-- Structure de la table `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `nom` varchar(50) CHARACTER SET latin1 NOT NULL,
  `password` varchar(255) CHARACTER SET latin1 NOT NULL,
  `email` varchar(255) CHARACTER SET latin1 NOT NULL,
  `adresse` varchar(255) NOT NULL,
  `ville` varchar(100) NOT NULL,
  `codepostale` int(5) NOT NULL,
  `token` varchar(255) NOT NULL,
  `active` int(1) DEFAULT '0',
  `role` varchar(20) DEFAULT 'client'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `users`
--

INSERT INTO `users` (`id`, `nom`, `password`, `email`, `adresse`, `ville`, `codepostale`, `token`, `active`, `role`) VALUES
(6, 'Messi', '6e6deb8e629c2c919f1a543509fe63aa6e16fe4a', 'ahcene.kadi@laplateforme.io', '8 rue d\'hozier', 'Marseille', 13002, 'b4a07fde4f0c2a1df543f37b5c117ca1319e90b8', 1, 'admin'),
(7, 'Cristiano Ronaldo', 'ee9f0c3b64426a15df6f7b9bf6c51e224c665bff', 'cr7@cr7.com', '8 rue d\\\'hozier', 'Marseille', 13012, '9cffc5b590478e59e7c722d00261ea8a7c678af8', 1, 'admin'),
(42, 'zozo', 'af4e65aa629fd012903aff86fd8a5d49b05a5e65', 'kapelloj4@hotmail.fr', '8 rue d\'hozier', 'Marseille', 13002, 'db84e35b33259c1dfb2f482e364a3e765dc8c21a', 0, NULL),
(44, 'Junior Neymar', 'e93668f8f5f5829be715d0aebcf5e23d143d855f', 'neymar@neymar.com', '8 rue d\'hozier', 'Marseille', 13002, 'ff47bd119b78916c999c0e4a97c9bd1803f7da40', 1, 'admin');

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `categories`
--
ALTER TABLE `categories`
  ADD PRIMARY KEY (`id`);

--
-- Index pour la table `orders`
--
ALTER TABLE `orders`
  ADD PRIMARY KEY (`id`);

--
-- Index pour la table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`);

--
-- Index pour la table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `categories`
--
ALTER TABLE `categories`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT pour la table `orders`
--
ALTER TABLE `orders`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=34;

--
-- AUTO_INCREMENT pour la table `products`
--
ALTER TABLE `products`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=59;

--
-- AUTO_INCREMENT pour la table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=45;
